In [2]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
my_secret

[1, 57, 71, 127, 141, 197, 211, 267, 281]

In [3]:
import numpy as np

np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

## 9.3

In [5]:
my_array = np.array([x for x in range(10)])
my_array[5]
my_array[-1]
my_array[3:6]
my_array[1:8:3]

array([1, 4, 7])

In [95]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

## 9.3.1
Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [96]:
sub_secret = big_secret[:,-1:]
sub_secret

array([[ 294.       ],
       [  33.1662479],
       [2500.       ],
       [  33.1662479],
       [ 294.       ]])

In [97]:
sub_secret_sum = sum(sub_secret)
sub_secret_sum

array([3154.33249581])

In [98]:
round(sub_secret_sum[0], 2)

3154.33

## 9.3.2
Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [99]:
sub_secret = big_secret[:,0:5]
sub_secret

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

In [101]:
sub_secret_sum = 0
for i in range(0, 5):
    sub_secret_sum += sub_secret[i,i]
    
round(sub_secret_sum, 2)

121.37

## 9.3.3
Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [102]:
sub_secret = big_secret[:,-5:]
sub_secret

array([[ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [2116.        , 2209.        , 2304.        , 2401.        ,
        2500.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ]])

In [105]:
sub_secret_sum = sub_secret[0,0]
for i in range(1, 5):
    sub_secret_sum *= sub_secret[i,i]
    
sub_secret_sum

341505315559.2347

Продолжим работать с массивом big_secret. Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [110]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [111]:
odd_slice = big_secret[1::2,1::2]
odd_slice[:] = 1
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 1.00000000e+00, 3.16859590e+01, 1.00000000e+00,
       

In [112]:
even_slice = big_secret[::2,::2]
even_slice[:] = -1
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

## 9.3.4
Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [113]:
sub_secret = big_secret[:,:5]
sub_secret

array([[-1.        , 10.        , -1.        , 56.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        ,  1.        , -1.        ,  9.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        , 10.        , -1.        , 56.        , -1.        ]])

In [114]:
sub_secret_sum = 0
for i in range(0, 5):
    sub_secret_sum += sub_secret[i,i]
    
sub_secret_sum

-1.0

## 9.3.5
Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [115]:
sub_secret = big_secret[:,-5:]
sub_secret

array([[-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.20900000e+03, -1.00000000e+00,
         2.40100000e+03, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00]])

In [116]:
sub_secret_sum = sub_secret[0,0]
for i in range(1, 5):
    sub_secret_sum *= sub_secret[i,i]
    
sub_secret_sum

-1.0

In [2]:
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [3]:
great_secret

array([[ 0.        ,  4.64158883, 66.66666667],
       [ 1.        ,  4.65700951, 40.        ],
       [ 1.41421356,  4.67232873, 67.33333333],
       [ 1.73205081,  4.68754815, 40.4       ],
       [ 2.        ,  4.70266938, 68.        ],
       [ 2.23606798,  4.71769398, 40.8       ],
       [ 2.44948974,  4.73262349, 68.66666667],
       [ 2.64575131,  4.7474594 , 41.2       ],
       [ 2.82842712,  4.76220316, 69.33333333],
       [ 3.        ,  4.77685618, 41.6       ],
       [ 3.16227766,  4.79141986, 70.        ],
       [ 3.31662479,  4.80589553, 42.        ],
       [ 3.46410162,  4.82028453, 70.66666667],
       [ 3.60555128,  4.83458813, 42.4       ],
       [ 3.74165739,  4.84880759, 71.33333333],
       [ 3.87298335,  4.86294413, 42.8       ],
       [ 4.        ,  4.87699896, 72.        ],
       [ 4.12310563,  4.89097325, 43.2       ],
       [ 4.24264069,  4.90486813, 72.66666667],
       [ 4.35889894,  4.91868473, 43.6       ],
       [ 4.47213595,  4.93242415, 73.333

In [4]:
great_secret.shape

(100, 3)

## 9.4.2
Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [5]:
cos_sum = sum(np.cos(great_secret[0,:]))
round(cos_sum, 2)

0.16

## 9.4.3
Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [6]:
result = sum(great_secret[great_secret>50])
result

5470.0

## 9.4.4
Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [7]:
flat_array = great_secret.flatten()
flat_array[150]

7.0710678118654755

## 9.4.5
Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [12]:
sorted_array = np.sort(great_secret, axis=0)
result = sum(sorted_array[-1,:])
round(result, 2)

115.12

## 9.5

In [28]:
import pandas as pd

students_df = pd.read_csv('../data/students.csv')
students_df

ID (номер в журнале)  Рост, см  Масса тела, кг  Средний балл
0                     1       135              34           4.0
1                     2       160              43           5.0
2                     3       163              40           4.3
3                     4       147              44           5.0
4                     5       138              41           4.7
5                     6       149              54           3.9
6                     7       136              39           4.2
7                     8       154              48           4.9
8                     9       137              35           3.7
9                    10       165              60           4.6

In [29]:
# Convert dataframe to array.
students = students_df.to_numpy()

In [30]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [31]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [32]:
median = np.median(students[:,-1])
median

4.449999999999999

In [33]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

## 9.5.1
Чему равно медианное значение массы тела школьников?

In [36]:
median_weight = np.median(students[:,2])
median_weight

42.0

## 9.5.2
На сколько среднее арифметическое массы тела школьников больше медианного значения для этого же показателя? Дайте ответ в килограммах с точностью до одной десятой кг.

In [35]:
mean_weight = np.mean(students[:,2])
mean_weight

43.8

In [39]:
weight_diff = mean_weight - median_weight
round(weight_diff, 1)

1.8

Давайте узнаем, как связан рост и вес наших школьников, посчитав коэффициент корреляции столбцов матрицы:

In [40]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.64314431],
       [0.64314431, 1.        ]])

Полученный нами коэффициент корреляции составляет чуть больше 0.64. Это говорит о том, что между ростом и весом школьников существует положительная связь: более рослые ученики обычно имеют более высокую массу тела.

## 9.5.3
Между какой парой признаков в массиве students наблюдается минимальная корреляция?

In [44]:
# Рост и средний балл.
corr_hm = np.corrcoef(students[:,1], students[:,3])
corr_hm

array([[1.        , 0.46293714],
       [0.46293714, 1.        ]])

In [45]:
# Вес и средний балл.
corr_wm = np.corrcoef(students[:,2], students[:,3])
corr_wm

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

## 9.5.4
Используя имеющийся набор данных о школьниках, найдите, чему равно стандартное отклонение их средних баллов.

In [46]:
std = np.std(students[:,-1])
std

0.4517742799230607

## 9.5.5
Посчитайте, чему равна дисперсия значений веса школьников.

Эту величину можно получить двумя способами: математически - используя определение дисперсии и известную функцию в блоке, или самостоятельно - используя подходящую функцию модуля NumPy.

In [75]:
"""Способ 1."""
"""Стандартное отклонение равно квадратному корню из дисперсии."""

# Получим стандартное отклонение по весу.
std = np.std(students[:,2])
print('Стандартное отклонение: {}'.format(std))

d = (std)**2
print('Дисперсия значений веса школьников: {}'.format(d))

Стандартное отклонение: 7.769169839822013
Дисперсия значений веса школьников: 60.36


## 9.7.4
Перед вами массив my_array, созданный с помощью кода выше. Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

Код должен содержать имя массива и набор индексов для получения нужного среза. В ответе использовать только положительные значения индексов и введите ответ в одну строку без пробелов.

In [76]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [80]:
my_array[1:-1,1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [82]:
my_array[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

## 9.7.5
Создайте массив my_sin, состоящий из синусов элементов массива my_array. Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до трёх цифр после запятой.

In [83]:
my_sin = np.sin(my_array)
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [87]:
result = np.sum(my_sin)
round(result, 3)

-0.058

## 9.7.6
Замените элементы в центральном фрагменте 3 х 3 массива my_sin на единицы.Чему равна сумма элементов изменённого массива? Ответ округлите до трёх знаков после запятой.

In [150]:
my_sin_ones = my_sin[1:4,1:4]
my_sin_ones

array([[ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.53657292,  0.42016704,  0.99060736],
       [-0.96139749, -0.75098725,  0.14987721]])

In [151]:
my_sin_ones[:] = 1
my_sin_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [152]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [153]:
result = np.sum(my_sin)
round(result, 3)

7.572

## 9.7.7
Преобразуйте первые 4 столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива? Ответ округлите до трёх заков после запятой.

In [154]:
my_sin_sliced = my_sin[:,0:4]
my_sin_sliced

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ,  1.        ,  1.        ],
       [-0.99999021,  1.        ,  1.        ,  1.        ],
       [-0.28790332,  1.        ,  1.        ,  1.        ],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [155]:
my_sin_sliced.shape

(5, 4)

In [156]:
my_sin_reshaped = np.reshape(my_sin_sliced, (10, 2))
my_sin_reshaped

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

In [157]:
my_sin_reshaped[:, 0]

array([ 0.84147098,  0.14112001, -0.2794155 ,  1.        , -0.99999021,
        1.        , -0.28790332,  1.        ,  0.83665564, -0.8462204 ])

In [158]:
result = np.sum(my_sin_reshaped[:,0])
round(result, 3)

2.406

Подготовка массива к заданиям 8-10

Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.

In [176]:
# bigdata_legacy = [x**2 for x in range(101, 1001, 2)]
# bigdata_legacy

bigdata = np.arange(101, 1001, 2)**2
bigdata

array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

In [177]:
median = np.median(bigdata)
median

302501.0

In [178]:
std = np.std(bigdata)
std

292095.0301991155

In [179]:
round(std)

292095.0

## 9.7.10
Чему равен коэффициент корреляции между элементами массива bigdata с чётными и нечётными индексами? Введите полученный ответ без изменений и округлений.

In [183]:
corr = np.corrcoef(bigdata[::2], bigdata[1::2])
corr

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])